peakProgram: peaksearch
threshold: 0.05
thresholdRatio: -1
maxRfactor: 0.5
boxsize: 10
max_number: 300
min_separation: 10
peakShape: Lorentzian
saveFolder: /eagle/APSDataAnalysis/hparraga/laue-indexing/output/txts/
filefolder: /eagle/APSDataAnalysis/LAUE/repacks_manual/repacks_100mn_thresh_10
filenamePrefix: out_
geoFile: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/xml_index/geoN_2023-02-07_19-19-10.xml
crystFile: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/xml_index/Ni.xml
scanPointStart: 0
scanPointEnd: 150
depthRangeStart: 0
depthRangeEnd: 201
detectorCropX1: 0 #min 0 max 2047
detectorCropX2: 2047
detectorCropY1: 0
detectorCropY2: 2047
pathbins: /eagle/APSDataAnalysis/hparraga/laue-indexing/
min_size: 1.13
max_peaks: 300
smooth: 0
maskFile: ''
indexKeVmaxCalc: 18.2
indexKeVmaxTest: 40.0
indexAngleTolerance: 0.1
indexH: 1
indexK: 1
indexL: 1
indexCone: 72.0
energyUnit: keV
exposureUnit: sec
cosmicFilter: True
num: 1 #TODO pattern number should be parsed out
recipLatticeUnit: 1/nm
latticeParametersUnit: nm
xmlOutFile: /eagle/APSDataAnalysis/hparraga/laue-indexing/output/repacks_100mn_thresh_10.xml
errorLog: /eagle/APSDataAnalysis/hparraga/laue-indexing/output/error.log