peakProgram: peaksearch
threshold: 20.0
thresholdRatio: -1
maxRfactor: 0.8
boxsize: 5
max_number: 200
min_separation: 20
peakShape: Lorentzian
saveFolder: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/results/out_index1/
peaksPrefix: peaks_
filefolder: /data/laue34/repacks_10mn/consgeo/
filename: out_
geoFile: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/xml_index/geoN_2023-02-07_19-19-10.xml
crystFile: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/xml_index/Ni.xml
scanPointStart: 0
scanPointEnd: 150
depthRangeStart: 0
depthRangeEnd: 201
detectorCropX1: 0 #min 0 max 2047
detectorCropX2: 2047
detectorCropY1: 0
detectorCropY2: 2047
pathbins: /data/laue34/LaueIndex_XML_python/Example/jupyter_files/py_func/linux/
min_size: 1.13
max_peaks: 300
smooth: 1
maskFile: ''
indexKeVmaxCalc: 17.2
indexKeVmaxTest: 35.0
indexAngleTolerance: 0.1
indexH: 0
indexK: 0
indexL: 2
indexCone: 72.0
energyUnit: keV
exposureUnit: sec
cosmicFilter: True
num: 1 #TODO pattern number should be parsed out
recipLatticeUnit: 1/nm
latticeParametersUnit: nm
xmlOutFile: testXML.xml
errorLog: error.log