name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        
    - name: Install MPI and scientific dependencies
      run: |
        # Update package lists
        sudo apt-get update
        
        # Install OpenMPI
        sudo apt-get install -y openmpi-bin libopenmpi-dev
        
        # Install GSL (GNU Scientific Library)
        sudo apt-get install -y libgsl-dev
        
        # Install HDF5
        sudo apt-get install -y libhdf5-dev hdf5-tools
        
        # Install Python packages
        pip install mpi4py h5py

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install project package
      run: |
        # Install the project package in editable mode
        # This step may fail if there are compilation issues
        pip install -e .

    - name: Test with unittest
      run: |
        python -m unittest discover -v -s tests
